blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/VVTJhkKc4G
    about: Please visit the Carolina Development Discord server for questions and support requests.